### ISSUE TITLE
Request to add controller.

### ISSUE THREAD

**Issue by abhishekove** [MaiaraM/banner_carousel#1]
Please add access to the page controller. To control the pages programmatically.

**Comment by MaiaraM** [comment]
This is a good request, I will upload a new version today with these features

**Comment by abhishekove** [comment]
I have almost programmed it. Will give a pull request by today itself.

**Comment by MaiaraM** [comment]
I just updated to the new version 1.2.0. I hope it solves

**Comment by abhishekove** [comment]
Can you please check my pull request? I think it will give better abstraction. We can use the stream for any future change. May allow passing JSON/Class variable and access different functions based on the case.
